/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author gauravpunjabi
 */
public class Encrypting extends javax.swing.JFrame {

    /**
     * Creates new form Encrypting
     */
    public Encrypting() {
        initComponents();
        this.setSize(800,600);
    }
    public void setTitle(String title)
    {
        jlTitle.setText("Please wait while we " + title + " your data.");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlAnimation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setShape(new RoundRectangle2D.Double(0,0,800,550,30,30));
        getContentPane().setLayout(null);

        jlTitle.setFont(new java.awt.Font("Raleway", 0, 38)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(255, 255, 255));
        jlTitle.setText("Please wait while we Encrypt your Data.");
        getContentPane().add(jlTitle);
        jlTitle.setBounds(60, 70, 702, 45);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/cancel.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(756, 10, 32, 32);

        jlAnimation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/EncryptionAnimation.gif"))); // NOI18N
        jlAnimation.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlAnimationMouseDragged(evt);
            }
        });
        jlAnimation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlAnimationMousePressed(evt);
            }
        });
        getContentPane().add(jlAnimation);
        jlAnimation.setBounds(0, 0, 800, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlAnimationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAnimationMousePressed
        this.x = evt.getX();
        this.y = evt.getY();
    }//GEN-LAST:event_jlAnimationMousePressed

    private void jlAnimationMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAnimationMouseDragged
        this.setLocation(evt.getXOnScreen()-x,evt.getYOnScreen()-y);
    }//GEN-LAST:event_jlAnimationMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encrypting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encrypting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encrypting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encrypting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encrypting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlAnimation;
    private javax.swing.JLabel jlTitle;
    // End of variables declaration//GEN-END:variables
    private int x,y;
}
